# Generated by Django 4.2 on 2024-02-09 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_alter_category_name'),
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.exam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='master.category'),
        ),
        migrations.AddField(
            model_name='exam',
            name='type_of_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.moduletype'),
        ),
        migrations.AddField(
            model_name='fulllengthtest',
            name='test_type',
            field=models.ForeignKey(help_text='IELTS/PTE etc', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.testtype'),
        ),
        migrations.AddField(
            model_name='fulllengthtest',
            name='writing',
            field=models.ManyToManyField(blank=True, limit_choices_to={'exam_type': 'Writing'}, null=True, related_name='writing', to='exam.exam'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('exam', 'question_number')},
        ),
    ]
