# Generated by Django 4.2 on 2024-02-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_answer_exam_exam_exam_category_exam_type_of_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='array',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
