# Generated by Django 4.2 on 2024-02-17 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_exam_array'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='array',
            new_name='question_structure',
        ),
    ]
