# Generated by Django 4.2 on 2024-02-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_rename_array_exam_question_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing'), ('General', 'General')], default='Reading', help_text='(Reading, Listening, Speaking, Writing)', max_length=200, null=True),
        ),
    ]
