# Generated by Django 4.2 on 2024-02-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='passage_image',
            field=models.ImageField(blank=True, null=True, upload_to='passage-images'),
        ),
    ]
