# Generated by Django 4.2 on 2024-02-26 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_exam_passage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='audio_file',
            field=models.ImageField(blank=True, null=True, upload_to='examblockaudio/'),
        ),
    ]
