# Generated by Django 4.2 on 2024-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing'), ('General', 'General'), ('AWA', 'AWA'), ('Integrated-Reasoning', 'Integrated-Reasoning'), ('Quantitative-Reasoning', 'Quantitative-Reasoning'), ('Verbal-Reasoning', 'Verbal-Reasoning')], default='Reading', help_text='(Reading, Listening, Speaking, Writing)', max_length=200, null=True),
        ),
    ]
