# Generated by Django 4.2 on 2024-04-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_alter_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_category',
            field=models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('GRE', 'GRE'), ('TOFEL', 'TOFEL'), ('GMAT', 'GMAT'), ('PTE', 'PTE'), ('GENERAL', 'GENERAL'), ('DUOLINGO', 'DUOLINGO')], max_length=100, null=True),
        ),
    ]
