# Generated by Django 4.2 on 2024-04-16 17:41

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_alter_exam_exam_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('difficulty_level', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=200, null=True)),
                ('block_threshold', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'speaking_block',
            },
        ),
        migrations.CreateModel(
            name='SpeakingBlockAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('speaking_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.speakingblock')),
            ],
        ),
    ]
