# Generated by Django 4.2 on 2024-04-16 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_speakingblock_speakingblockanswer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SpeakingBlockAnswer',
            new_name='SpeakingBlockQuestion',
        ),
    ]
