# Generated by Django 4.2 on 2024-04-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_rename_speakingblockanswer_speakingblockquestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingblockquestion',
            name='speaking_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exam.speakingblock'),
        ),
    ]
