# Generated by Django 4.2 on 2024-04-19 16:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_alter_speakingblockquestion_speaking_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingblock',
            name='difficulty_level',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Hard', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speakingblock',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='speakingblockquestion',
            name='question',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
