# Generated by Django 4.2 on 2024-04-20 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_alter_speakingblock_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingblockquestion',
            name='question_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
