# Generated by Django 4.2 on 2024-02-26 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_exam_block',
            new_name='student_mock_test',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_module',
            new_name='student_pt_flt',
        ),
    ]
