# Generated by Django 4.2 on 2024-02-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_rename_student_exam_block_student_student_mock_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_pt_flt',
            new_name='student_flt',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_mock_test',
            new_name='student_pt',
        ),
    ]
