# Generated by Django 4.2 on 2024-02-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0006_rename_a_w_a_module_awa'),
        ('students', '0003_rename_student_pt_flt_student_student_flt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_pt',
            field=models.ManyToManyField(blank=True, null=True, related_name='+', to='Create_Test.module'),
        ),
    ]
