# Generated by Django 4.2 on 2024-02-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0007_alter_module_exam_test'),
        ('students', '0004_alter_student_student_pt'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_mock',
            field=models.ManyToManyField(blank=True, null=True, related_name='mock', to='Create_Test.module'),
        ),
    ]
