# Generated by Django 4.2 on 2024-04-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0017_alter_module_practice_test_type'),
        ('students', '0006_alter_student_student_mock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_flt',
            field=models.ManyToManyField(blank=True, null=True, to='Create_Test.fulllengthtest'),
        ),
    ]
