# Generated by Django 4.2 on 2024-05-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_speakingblockquestion_question_number'),
        ('students', '0008_student_student_flt_student_student_mock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_speakingblock',
            field=models.ManyToManyField(blank=True, null=True, related_name='speakingblock', to='exam.speakingblock'),
        ),
    ]
