# Generated by Django 4.2 on 2024-05-29 16:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_student_student_speakingblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='active_tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=2),
        ),
    ]
