# Generated by Django 4.2 on 2024-05-29 17:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_student_active_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='active_tokens',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), default=list, size=2),
        ),
    ]
