version: '3.8'
services:
  postgres_db:
    image: postgres:latest
    restart: on-failure
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      
    ports:
      - "5555:5432"
    
    expose:
      - "5432"
    volumes: 
      - pgdb:/var/lib/postgresql/data
  backend:
    build: .
    restart: on-failure
    container_name: lmss
    ports:
      - "8000:8000"
      - "8888:8888"
    command: sh -c "supervisord -c supervisord.conf -n &"
    expose:
      - "8000"

    volumes:
      - ./:/app
      - staticfiles:/var/www/static/
      - media:/var/www/media/
      # - /var/certbot/conf:/etc/letsencrypt/:ro
    env_file:
      - .env
    environment:
      - STATIC_ROOT=/var/www/static/

    depends_on:
      - postgres_db

  nginx:
    build: ./nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - staticfiles:/home/app/staticfiles/
      - media:/home/app/media/
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certificates/:/etc/nginx/certificates/
      - /home/studystreak/StudyStreak/build/:/home/studystreak/
    depends_on:
      - backend
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
    expose:
      - 6379
volumes:
  pgdb:
  staticfiles:
  media:
  cache:
    driver: local