# Generated by Django 4.2 on 2024-02-25 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0002_live_class_liveclasstype_live_class_select_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_class',
            name='registration_limit',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
