# Generated by Django 4.2 on 2024-02-25 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0003_live_class_registration_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live_class',
            name='registration_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
