# Generated by Django 4.2 on 2024-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0004_alter_live_class_registration_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='live_class',
            name='bookslot_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
