# Generated by Django 4.2 on 2024-03-17 12:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0006_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('student', 'live_class'), name='unique_intro', violation_error_message='You have already added note for this class'),
        ),
    ]
