# Generated by Django 4.2 on 2024-03-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LiveClass', '0007_rename_user_note_student_alter_note_note_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
