# Generated by Django 4.2 on 2024-02-09 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='primary_instructor',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ManyToManyField(blank=True, limit_choices_to={'groups__name': 'Tutor'}, related_name='tutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
