# Generated by Django 4.2 on 2024-02-25 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('Courses', '0003_alter_course_primary_instructor_alter_course_tutor'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeDataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField()),
                ('lesson_id', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'youtubeDataRecord',
            },
        ),
    ]
