# Generated by Django 4.2 on 2024-02-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0003_lesson_section'),
        ('Courses', '0004_youtubedatarecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubedatarecord',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='youtubedatarecord',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_data', to='coursedetail.lesson'),
        ),
    ]
