# Generated by Django 4.2 on 2024-03-14 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_remove_youtubedatarecord_lesson_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Course_Overview_Provider',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_Overview_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
