# Generated by Django 4.2 on 2024-04-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0006_alter_course_course_overview_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubedatarecord',
            name='timestamp',
            field=models.CharField(max_length=255),
        ),
    ]
