# Generated by Django 4.2 on 2024-02-08 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponses', '0002_alter_studentanswer_exam_alter_studentanswer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_answer',
            old_name='student_exam',
            new_name='student_answers',
        ),
    ]
