# Generated by Django 4.2 on 2024-02-08 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createexam',
            name='IELTS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Create_Test.module'),
        ),
    ]
