# Generated by Django 4.2 on 2024-02-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0003_module_listening_module_reading_module_speaking_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Create Practice Test', 'verbose_name_plural': 'Create Practice Tests'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='module_category',
        ),
    ]
