# Generated by Django 4.2 on 2024-02-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_exam_exam_type'),
        ('Create_Test', '0004_alter_module_options_remove_module_module_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='a_w_a',
            field=models.ManyToManyField(blank=True, null=True, related_name='a_w_a+', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='module',
            name='integrated_reasoning',
            field=models.ManyToManyField(blank=True, null=True, related_name='integrated_reasoning+', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='module',
            name='quantitative_reasoning',
            field=models.ManyToManyField(blank=True, null=True, related_name='quantitative_reasoning+', to='exam.exam'),
        ),
        migrations.AddField(
            model_name='module',
            name='verbal_reasoning',
            field=models.ManyToManyField(blank=True, null=True, related_name='verbal_reasoning+', to='exam.exam'),
        ),
    ]
