# Generated by Django 4.2 on 2024-02-22 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0005_module_a_w_a_module_integrated_reasoning_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='a_w_a',
            new_name='awa',
        ),
    ]
