# Generated by Django 4.2 on 2024-02-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0006_rename_a_w_a_module_awa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='exam_test',
            field=models.CharField(blank=True, choices=[('Practice', 'Practice'), ('Full Length', 'Full Length'), ('Mock Test', 'Mock Test')], max_length=20, null=True),
        ),
    ]
