# Generated by Django 4.2 on 2024-03-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0008_alter_module_exam_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullLengthTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_listening', to='Create_Test.module')),
                ('reading_set', models.ForeignKey(blank=True, limit_choices_to={'Reading__exam_type': 'Reading'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_reading', to='Create_Test.module')),
                ('speaking_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_speaking', to='Create_Test.module')),
                ('writing_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_writing', to='Create_Test.module')),
            ],
        ),
    ]
