# Generated by Django 4.2 on 2024-03-02 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0009_fulllengthtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulllengthtest',
            name='listening_set',
            field=models.ForeignKey(blank=True, limit_choices_to={'Listening__exam_type': 'Listening'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_listening', to='Create_Test.module'),
        ),
        migrations.AlterField(
            model_name='fulllengthtest',
            name='speaking_set',
            field=models.ForeignKey(blank=True, limit_choices_to={'Speaking__exam_type': 'Speaking'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_speaking', to='Create_Test.module'),
        ),
        migrations.AlterField(
            model_name='fulllengthtest',
            name='writing_set',
            field=models.ForeignKey(blank=True, limit_choices_to={'Writing__exam_type': 'Writing'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_writing', to='Create_Test.module'),
        ),
    ]
