# Generated by Django 4.2 on 2024-03-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0011_fulllengthtest_difficulty_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fulllengthtest',
            name='listening_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_listening', to='Create_Test.module'),
        ),
        migrations.AlterField(
            model_name='fulllengthtest',
            name='reading_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_reading', to='Create_Test.module'),
        ),
        migrations.AlterField(
            model_name='fulllengthtest',
            name='speaking_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_speaking', to='Create_Test.module'),
        ),
        migrations.AlterField(
            model_name='fulllengthtest',
            name='writing_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flt_writing', to='Create_Test.module'),
        ),
    ]
