# Generated by Django 4.2 on 2024-03-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0012_alter_fulllengthtest_listening_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulllengthtest',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
