# Generated by Django 4.2 on 2024-03-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0013_fulllengthtest_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='practice_test_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
