# Generated by Django 4.2 on 2024-03-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0015_alter_module_practice_test_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='practice_test_type',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing'), ('AWA', 'AWA'), ('Integrated Reasoning', 'Integrated Reasoning'), ('Quantitative Reasoning', 'Quantitative Reasoning'), ('Verbal Reasoning', 'Verbal Reasoning')], default='Reading', max_length=50, null=True),
        ),
    ]
