# Generated by Django 4.2 on 2024-04-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0017_alter_module_practice_test_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='Speaking',
        ),
    ]
