# Generated by Django 4.2 on 2024-04-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_alter_speakingblock_difficulty_level_and_more'),
        ('Create_Test', '0018_remove_module_speaking'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='Speaking',
            field=models.ManyToManyField(blank=True, null=True, related_name='Speaking+', to='exam.speakingblock'),
        ),
    ]
