# Generated by Django 4.2 on 2024-02-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0002_studentanswer_exam_studentanswer_user_student_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='band',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
