# Generated by Django 4.2 on 2024-02-18 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0006_remove_student_answer_answer_audio_speakingresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='gpt_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
