# Generated by Django 4.2 on 2024-02-21 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0008_alter_studentanswer_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='band',
            new_name='bands',
        ),
    ]
