# Generated by Django 4.2 on 2024-02-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0009_rename_band_studentanswer_bands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='bands',
        ),
    ]
