# Generated by Django 4.2 on 2024-03-01 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_exam_exam_category'),
        ('Create_Test', '0008_alter_module_exam_test'),
        ('ExamResponse', '0013_alter_studentanswer_band'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentanswer',
            old_name='gpt_response',
            new_name='AI_Assessment',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='Full_Length_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gull_length+', to='Create_Test.module'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='Practise_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Create_Test.module'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='Tutor_Assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='exam.exam'),
        ),
    ]
