# Generated by Django 4.2 on 2024-03-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0014_rename_gpt_response_studentanswer_ai_assessment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingresponse',
            name='question_number',
        ),
        migrations.AlterField(
            model_name='speakingresponse',
            name='student_answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='ExamResponse.studentanswer'),
        ),
    ]
