# Generated by Django 4.2 on 2024-03-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0015_remove_speakingresponse_question_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingresponse',
            name='question_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
