# Generated by Django 4.2 on 2024-03-01 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0016_speakingresponse_question_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingresponse',
            name='student_answers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='ExamResponse.studentanswer'),
        ),
    ]
