# Generated by Django 4.2 on 2024-03-01 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0017_alter_speakingresponse_student_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingresponse',
            name='student_answers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='student_exams', to='ExamResponse.studentanswer'),
            preserve_default=False,
        ),
    ]
