# Generated by Django 4.2 on 2024-03-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0021_alter_speakingresponse_answer_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingresponse',
            name='answer_audio',
            field=models.FileField(upload_to=''),
        ),
    ]
