# Generated by Django 4.2 on 2024-03-02 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0022_alter_speakingresponse_answer_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='Full_Length_Exam',
        ),
    ]
