# Generated by Django 4.2 on 2024-03-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0010_alter_fulllengthtest_listening_set_and_more'),
        ('ExamResponse', '0023_remove_studentanswer_full_length_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='Full_Length_Exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_length+', to='Create_Test.fulllengthtest'),
        ),
    ]
