# Generated by Django 4.2 on 2024-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0024_studentanswer_full_length_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing'), ('General', 'General'), ('a_w_a', 'a_w_a'), ('integrated_reasoning', 'integrated_reasoning'), ('quantitative_reasoning', 'quantitative_reasoning'), ('verbal_reasoning', 'verbal_reasoning')], max_length=30, null=True),
        ),
    ]
