# Generated by Django 4.2 on 2024-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0025_studentanswer_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakingresponse',
            name='answer_audio',
            field=models.FileField(upload_to='speaking-response/'),
        ),
    ]
