# Generated by Django 4.2 on 2024-03-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0026_alter_speakingresponse_answer_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_answer',
            name='answer_text',
            field=models.TextField(blank=True),
        ),
    ]
