# Generated by Django 4.2 on 2024-03-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0027_alter_student_answer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_answer',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
