# Generated by Django 4.2 on 2024-03-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0028_alter_student_answer_answer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing'), ('General', 'General'), ('AWA', 'AWA'), ('Integrated Reasoning', 'Integrated Reasoning'), ('Quantitative Reasoning', 'Quantitative Reasoning'), ('Verbal Reasoning', 'Verbal Reasoning')], max_length=30, null=True),
        ),
    ]
