# Generated by Django 4.2 on 2024-03-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0029_alter_studentanswer_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentanswer',
            name='exam_type',
            field=models.CharField(blank=True, choices=[('Reading', 'Reading'), ('Listening', 'Listening'), ('Speaking', 'Speaking'), ('Writing', 'Writing'), ('General', 'General'), ('AWA', 'AWA'), ('Integrated-Reasoning', 'Integrated-Reasoning'), ('Quantitative-Reasoning', 'Quantitative-Reasoning'), ('Verbal-Reasoning', 'Verbal-Reasoning')], max_length=30, null=True),
        ),
    ]
