# Generated by Django 4.2 on 2024-04-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_alter_speakingblockquestion_speaking_block'),
        ('ExamResponse', '0031_alter_studentanswer_band'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakingBlockAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('answer_audio', models.FileField(upload_to='speaking-response/')),
                ('speaking_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.speakingblock', verbose_name='speakng block')),
            ],
            options={
                'verbose_name': 'Speaking Block Answers',
            },
        ),
    ]
