# Generated by Django 4.2 on 2024-04-20 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0019_module_speaking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ExamResponse', '0032_speakingblockanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speakingblockanswer',
            options={'verbose_name': 'Speaking Block Answer'},
        ),
        migrations.AddField(
            model_name='speakingblockanswer',
            name='flt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_length+', to='Create_Test.fulllengthtest'),
        ),
        migrations.AddField(
            model_name='speakingblockanswer',
            name='practise_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Create_Test.module'),
        ),
        migrations.AddField(
            model_name='speakingblockanswer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
