# Generated by Django 4.2 on 2024-04-20 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0034_alter_speakingblockanswer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingblockanswer',
            name='band',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=3),
            preserve_default=False,
        ),
    ]
