# Generated by Django 4.2 on 2024-04-20 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0035_speakingblockanswer_band'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingblockanswer',
            name='band',
        ),
        migrations.RemoveField(
            model_name='speakingblockanswer',
            name='flt',
        ),
    ]
