# Generated by Django 4.2 on 2024-04-20 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_alter_speakingblock_difficulty_level_and_more'),
        ('ExamResponse', '0036_remove_speakingblockanswer_band_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswer',
            name='speaking_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.speakingblock'),
        ),
    ]
