# Generated by Django 4.2 on 2024-04-20 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Create_Test', '0019_module_speaking'),
        ('exam', '0019_alter_speakingblock_difficulty_level_and_more'),
        ('ExamResponse', '0037_studentanswer_speaking_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingblockanswer',
            name='Flt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='full_length+', to='Create_Test.fulllengthtest'),
        ),
        migrations.AlterField(
            model_name='speakingblockanswer',
            name='speaking_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.speakingblock', verbose_name='speakng block'),
        ),
    ]
