# Generated by Django 4.2 on 2024-05-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0038_speakingblockanswer_flt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingblockanswer',
            name='AI_Assessment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speakingblockanswer',
            name='Tutor_Assessment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
