# Generated by Django 4.2 on 2024-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0039_speakingblockanswer_ai_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingblockanswer',
            name='band',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
