# Generated by Django 4.2 on 2024-05-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0040_speakingblockanswer_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakingblockanswer',
            name='exam_category',
            field=models.CharField(blank=True, choices=[('IELTS', 'IELTS'), ('GRE', 'GRE'), ('TOFEL', 'TOFEL'), ('GMAT', 'GMAT'), ('PTE', 'PTE'), ('GENERAL', 'GENERAL'), ('DUOLINGO', 'DUOLINGO')], max_length=100, null=True),
        ),
    ]
