# Generated by Django 4.2 on 2024-05-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamResponse', '0041_speakingblockanswer_exam_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakingblockanswer',
            name='exam_category',
        ),
    ]
