# Generated by Django 4.2 on 2024-02-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('coursedetail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_assignment',
            field=models.ManyToManyField(blank=True, null=True, related_name='lesson_assignment', to='exam.exam'),
        ),
    ]
