# Generated by Django 4.2 on 2024-03-18 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_student_mock'),
        ('coursedetail', '0006_remove_note_unique_intro_note_unique_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coursedetail.lesson'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
            preserve_default=False,
        ),
    ]
