# Generated by Django 4.2 on 2024-03-18 10:23

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0007_alter_note_lesson_alter_note_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
