# Generated by Django 4.2 on 2024-03-19 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0008_alter_note_note'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='note',
            name='unique_intro',
        ),
    ]
