# Generated by Django 4.2 on 2024-03-23 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursedetail', '0009_remove_note_unique_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
