# Generated by Django 4.2 on 2024-03-09 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0005_remove_youtubedatarecord_lesson_id_and_more'),
        ('gamification', '0002_gamification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCardItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveIndex(
            model_name='gamification',
            name='gamificatio_content_6d42c4_idx',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='flash_cards',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Courses.course'),
        ),
        migrations.AddField(
            model_name='flashcarditem',
            name='flash_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.flashcard'),
        ),
    ]
