# Generated by Django 4.2 on 2024-03-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_flashcarditem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='set_priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='flashcard',
            constraint=models.UniqueConstraint(fields=('course', 'set_priority'), name='unique_flashcard_title', violation_error_message='Can not set same priority for same course'),
        ),
    ]
