# Generated by Django 4.2 on 2024-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_flashcard_set_priority_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('points_required', models.PositiveIntegerField(default=0)),
                ('gamification_items', models.ManyToManyField(to='gamification.gamification')),
            ],
        ),
    ]
