# Generated by Django 4.2 on 2024-03-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_student_mock'),
        ('gamification', '0007_badge_next_badge'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gamification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.gamification')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
