# Generated by Django 4.2 on 2024-03-14 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_alter_pointhistory_options_pointhistory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcarditem',
            name='flash_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_card_items', to='gamification.flashcard'),
        ),
    ]
