# Generated by Django 4.2 on 2024-03-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0010_alter_flashcarditem_flash_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcarditem',
            old_name='content',
            new_name='back',
        ),
        migrations.AddField(
            model_name='flashcarditem',
            name='front',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
