# Generated by Django 4.2 on 2024-03-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('gamification', '0011_rename_content_flashcarditem_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamification',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gamification', to='contenttypes.contenttype'),
        ),
    ]
