name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy_on_Docker_VPS:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu #${{ secrets.USERNAME }}
          host: 65.20.73.247 #${{ secrets.HOST }}
          password: amitv9493 #${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/ubuntu/studystreak-new/studystreak

            git pull
